--- 
- name: Obtain ServiceNow Token
  hosts: localhost
  gather_facts: no

  vars:
   oauth_endpoint: "https://ipaastest-apis.eu1.ccp.capgemini.com/token"
   client_id: "InSjKoAdUmsMMGiifCo1QTZAhp4a" 
   client_secret: "XuKN3XLWbfT1AGFpI3fsek5HOxwa"

  tasks:
  - name: Get token from servicenow
    uri:
     url: "{{ oauth_endpoint }}"
     method: POST
     headers:
      Content-Type: "application/x-www-form-urlEncoded"
     body: "grant_type= "client_credentials"&client_id={{ client_id }}&client_secret={{ client_secret }}"
     status_code: 200
    register: response

  - name: Extract token from api response
    set_fact:
     servicenow_token: "{{ response.json.access.token }}"



  
- name: Create ServiceNow Incident
  hosts: localhost
  gather_facts: no
  vars:
   servicenow_api_url: "https://ipaastest-apis.eu1.ccp.capgemini.com/alert-business-service/alerts/event/update"
  tasks:
  - name: Create Incident in ServiceNow
    uri:
     url: "{{ servicenow_api_url }}"
     method: POST
     headers:
      Authorization: "Bearer {{ servicenow_token }}"
      Content-Type: "application/json"
     body_format: json
    # body: '{"short_description": "Incident Title test", "description":"Incident Description", "assigned_to":"Assigned User","urgency":"3","impact":"3"}'
     body: '{
       "header": {
       "topic": "cn/Capgemini Global Hub/de/dop/ic/%2B/tn/%2B/cs/cgsam/sp/%2B/at/%2B",
       "applicationId": "3879ed0f-2c0c-49d4-b868-625a5a726d55" },
       "body": {
       "companyName": "Capgemini Global Hub",
       "urgency": "3 - Medium",
       "impact": "3 - Moderate/Limited",
       "systemPlatform": "Windows",
       "impactedCi": "DSW12SQL01",
       "templateName": "CGSAM.Default",
       "externalSystemTicketId": "CoreOpTest_2023080216205109",
       "externalSystem": "Automation_EU",
       "shortDescription": "Correlation Testing",
       "fullDescription": "Correlation Testing",
       "customerShortname": "ADCUT11",
       "ipAddress": "",
       "alertId": ":USDAD-CITDEVOP7:NT:Windows_CPU_CRITICAL",
       "alertType": "Windows_CPU_CRITICAL",
       "correlationFlag": "2",
       "correlationId": "",
       "suppressionFlag": "Not in MWM",
       "suppressionId": "NULL",
      "deviceType": "",
      "modelClass": "",
      "modelType": "",
      "diskName": "C:",
      "memoryThreshold": "90",
      "serviceName": "",
      "cpuThreshold": ""
      }
      }'
     status_code: 200
    register: response

  - name: Check API response
    debug:
      var: response
    
