- name: Create Remediation Task
  hosts: localhost
  gather_facts: no

  tasks:
   - name: Define Remediation task data
     set_fact:
       task_data:
         name: "Remediation Task"
         description: "usecase triggered"
         target_hosts:
           - host1.example.com
           - host2.example.com
       remediation_command: " remediation command executed "

   - name: create remediation task via post api
     uri:
          url: "https://"
          method: POST
          headers: 
            Content-Type: "application/json"
            Authorization: "API_KEY"
          body_format: json
          body: "{{ task_data| to_json }}"
          return_content: yes
     register: api_response

   - name: Check API response status
     debug:
          msg: "Remediation task created successfully"
     when: api_response.status ==201

   - name: Check API response status
     fail:
          msg: "RFailed to create remediation task. Error: {{ api_response.json }}"
     when: api_response.status !=201
        
