--- 
- name: Obtain ServiceNow Token
  hosts: localhost
  gather_facts: no

  vars:
   oauth_endpoint: "https://ipaastest-apis.eu1.ccp.capgemini.com/token"
   client_id: "InSjKoAdUmsMMGiifCo1QTZAhp4a" 
   client_secret: "XuKN3XLWbfT1AGFpI3fsek5HOxwa"

  tasks:
  - name: Get token from servicenow
    uri:
     url: "{{ oauth_endpoint }}"
     method: POST
     headers:
      Content-Type: "application/x-www-form-urlEncoded"
     body: "grant_type= client_credentials&client_id={{ client_id }}&client_secret={{ client_secret }}"
     status_code: 200
    register: response

  - name: Extract token from api response
    set_fact:
     servicenow_token: "{{ response.json.access.token }}"



  
- name: Create ServiceNow Incident
  hosts: localhost
  gather_facts: no
  vars:
   servicenow_api_url: "https://ipaastest-apis.eu1.ccp.capgemini.com/api/now/table/incident"
  tasks:
  - name: Create Incident in ServiceNow
    uri:
     url: "{{ servicenow_api_url }}"
     method: POST
     headers:
      Authorization: "Bearer {{ servicenow_token }}"
      Content-Type: "application/json"
     body_format: json
    # body: '{"short_description": "Incident Title test", "description":"Incident Description", "assigned_to":"Assigned User","urgency":"3","impact":"3"}'
    body: '{"short_description": "Incident Title test", "urgency":"3","impact":"3"}'
     status code: 201
    register: response

  - name: Check API response
    debug:
      var: response
    
