---
- name: Example playbook using Tower credential variables
  hosts: localhost
  tasks:
    - name: Print Tower InstanceDetails Username
      debug:
        var: ansible_user

    - name: Print Tower InstanceDetails Password
      debug:
        var: ansible_pass
