---
- name: Accept and print JSON argument
  hosts: rhel
  gather_facts: false

  vars_prompt:
    - name: json_argument
      prompt: "Enter JSON argument"
      private: no

  tasks:
    - name: Set JSON argument
      set_fact:
        my_json: "{{ json_argument | from_json }}"

    - name: Print JSON argument
      debug:
        var: my_json
