---
- name: Accept and print argument
  hosts: rhel_hosts
  gather_facts: false

  vars:
    my_argument: ""
    
  tasks:
    - name: Print argument
      debug:
        msg: "The argument is: {{ my_argument }}"
