---
- name: Receive arguments from job template
  hosts: rhel_hosts
  gather_facts: false

  tasks:
    - name: Print arguments
      debug:
        msg: "param: {{ parameters }}, Platform: {{ Platform }}, Customer: {{ Customer }}"
