---
- name: Read sample csv file
  gather_facts: True
  hosts: localhost

  tasks:
  - name: "Reading csv information"
    read_csv:
      path: SampleCSV.csv
      register: usecaselist

  - debug: 
      msg: "{{ usecase.usecasename }} and value is {{ usecase.value }}"
      loop: "{{ usecaselist.list }}"
      loop_control:
        loop_var: usecase
