---
- name: Read sample csv file
  gather_facts: no
  hosts: localhost

  tasks:
    - name: install libraries
      pip: 
        name: pandas
        state: present

    - name:  import necessary python modules
      ansible.builtin.shell:
         cmd: "python -c 'import pandas as pd,requests'"

    - name:  download giturl
      get_url:
         url: "https://github.com/Navya-Gopu/Ansible/blob/main/samplecsv.csv"
         dest: "C:/Users/navygopu/Downloads/test/samplecsv.csv"
    - name: Reading csv information
      csvfile:
        path: "C:/Users/navygopu/Downloads/test/samplecsv.csv"
      register: usecase
     
    
      
    - name: print name
      debug:
        msg: "{{ usecase.list.0.usecasename }} and value is {{ usecase.list.0.value }}"
