---
- name: Read sample csv file
  gather_facts: True
  hosts: localhost

  tasks:
    - name: Reading csv information
      read_csv:
        path: SampleCSV.csv
      register: usecaselist
      
    - name: print name
      debug:
        msg: "{{ usecase.username }} and value is {{ usecase.password }}"
      loop: "{{ usecaselist.list }}"
      loop_control:
        loop_var: usecase
