---
- name: Read sample csv file
  gather_facts: no
  hosts: localhost

  tasks:
   - name: Read users from CSV file and return a list
     read_csv:
       path: samplecsv.csv
     register: users
     delegate_to: localhost
      
   - name: print name
     debug:
        msg: "{{ users.list.1.usecasename }} and value is {{ users.list.1.value }}"
