---
- name: Read sample csv file
  gather_facts: no
  hosts: localhost

  tasks:
    - name: Reading csv information
      read_csv:
        path: samplecsv.csv
      register: usecase
      
    - name: print name
      debug:
        msg: "{{ usecase.list.1.usecasename }} and value is {{ usecase.list.1.value }}"
