---
- name: Read content from CSV file
  hosts: localhost
  gather_facts: no

 

  tasks:
    - name: Read CSV file
      set_fact:
        csv_data: "{{ lookup('csvfile', 'path/to/samplecsv.csv', delimiter=',') }}"

 

    - name: Print CSV data
      debug:
        var: csv_data
