---
- name: Configuring Tenant with CSV file
  hosts: localhost
  gather_facts: false

  tasks:
  # Read a CSV file and access Tenant csv
  - name: Read data from CSV file to be used to configure ACI
    community.general.read_csv:
      path: samplecsv.csv
      # key: tenant
    register: mytenant
    delegate_to: localhost

  # Used for debugging purposes to make sure list is correct.
  - debug:
      msg: Tenant {{ mytenant.list.0.usecaseame }} and VRF {{ mytenant.list.0.value }}
