---
- name: Read users from CSV file and return a list
  community.general.read_csv:
    path: samplecsv.csv
  register: users
  delegate_to: localhost

- ansible.builtin.debug:
    msg: 'User {{ users.list.1.usecasename }} has UID {{ users.list.1.value }}'
