---
- name: Read sample csv file
  gather_facts: no
  hosts: localhost

  tasks:
    - name: install libraries
      pip: 
        name: pandas
        state: present

    - name:  import necessary python modules
      ansible.bultin.script:
         script: |
            import pandas as pd
     
    - name: Reading csv information
      csv_file:
        path: samplecsv.csv
      register: usecase
      
    - name: print name
      debug:
        msg: "{{ usecase.list.1.usecasename }} and value is {{ usecase.list.1.value }}"
