---
- name: Read sample csv file
  gather_facts: no
  hosts: localhost

  tasks:
    - name: install libraries
      pip: 
        name: pandas
        state: present

    - name:  import necessary python modules
      ansible.builtin.shell:
         cmd: "python -c 'import pandas as pd,requests'"
     
    - name: Reading csv information
      csv_file:
        path: samplecsv.csv
      register: usecase
      
    - name: print name
      debug:
        msg: "{{ usecase.list.1.usecasename }} and value is {{ usecase.list.1.value }}"
