---
- name: Using a REST API
  hosts: localhost
  gather_facts: false

  tasks:
    - debug:
        msg: “Let’s call an API”

    - name: To get inventories list from ansible tower
      uri:
        url: https://43.204.219.39/api/v2/inventories/
        method: GET
      register: results

    - debug:
        var: results.json.value
