---
- name: Process Incident Data
  hosts: localhost
  gather_facts: no

  tasks:
    # Import the 'snow.yml' playbook as a role
    - name: Import 'snow.yaml' as a role
      include_role:
        name: ./snow.yaml

    # Use the global variable from the imported playbook
    - name: Print Global Incident Data in Second Playbook
      debug:
        var: global_incident_data
