---
- name: Master playbook
  hosts: localhost
  become: yes
  tasks:
   - name: import sub playbook
     include_tasks: linux_is_alive_test.yml
     vars:
      # HOSTS: "15.206.82.173"
      name: : "Navya"
 
     
     
