---
- name: Master playbook
  hosts: "{{ HOSTS }}"
  become: yes
  tasks:
   - name: import sub playbook
     include_tasks: linux_is_alive_modified.yml
     vars:
         HOSTS: "{{ HOSTS }}"
     
 
     
     
