---
- name: Master playbook
  hosts: localhost
  become: yes
  tasks:
   - name: import sub playbook
     ansible.builtin.import_playbook: otherplays.yml
     vars:
         HOSTS: "{{ HOSTS }}"
     
 
     
     
