- name: Update ServiceNow SCTASK
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Task block with rescue
    block:
      - name: Include the generated token
        include_tasks: "Testtoken.yaml"
      - name: Construct URL with parameters
        set_fact:
          api_url: "{{ ipaas_uri }}/task-business-service/tasks/{{ sctask }}?uuid={{ uuid | urlencode }}&companyName={{ companyName | urlencode }}&fullResponse=true"
          action: "{{ action }}"
      ###################################################
      - name: Create Body for Assign Task
        set_fact:
          body: '{
        "state":  "{{ state }}",
        "workLogDescription":  {
                                   "workNotes":  "{{ workNotes }}"
                               },
        "taskCoordinator":  "{{ assignee }}"
    }'
        when: action == "assign"
      ###################################################
      - name: Create Body for Update Task
        set_fact:
          body: '{
        "workLogDescription":  {
                                   "workNotes":  "{{ workNotes }}"
                               }
    }'
        when: action == "update"
      ###################################################
      - name: Create Body for De-Assign Task
        set_fact:
          body: '{
        "workLogDescription":  {
                                   "workNotes":  "{{ workNotes }}"
                               },
        "taskCoordinator":  ""
    }'
        when: action == "deassign"
     ###################################################
      - name: Create Body for Resolve Task
        set_fact:
          body: '{
        "closeNotes":  "{{ closeNotes }}",
        "state":  "{{ state }}",
        "workLogDescription":  {
                                   "workNotes":  "{{ workNotes }}"
                               }
    }'
        when: action == "resolve"
    ###################################################
      - name: API Request
        uri:
         url: "{{ api_url }}"
         method: PATCH
         headers:
          Authorization: "Bearer {{ servicenow_token }}"
          Content-Type: "application/json"
         body_format: json
         body: "{{ body }}"
         status_code: 200
        register: result
        failed_when: result.status != 200
   ###################################################
      - name: Check API response
        debug:
          var: result
    
      - name: Check API response status
        debug:
              msg: "SCTASK updated successfully"
        when: result.status ==200
    rescue:
      - name: Check API response status
        fail:
             msg: "Failed to update SCTASK. Error: {{ result }}"
        when: result.status !=200
