---
- name: Linux Reboot
  hosts: rhel_hosts
  gather_facts: no
  remote_user: devops
  become: true
 
  tasks:
    - name: Reboot the machine (Wait for 90sec)
      reboot:
        reboot_timeout: 90
