- name: Update ServiceNow Incident
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Include the generated token
    include_tasks: "Testtoken.yaml"
  - name: Construct URL with parameters
    set_fact:
      api_url: "{{ ipaas_uri }}/incident-business-service/incidents/external/{{ incident }}?uuid={{ uuid | urlencode }}&companyName={{ companyName | urlencode }}"
      action: "{{ action }}"
  ###################################################
  - name: Assign Incident in ServiceNow
    uri:
     url: "{{ api_url }}"
     method: PATCH
     headers:
      Authorization: "Bearer {{ servicenow_token }}"
      Content-Type: "application/json"
     body_format: json
     body: '{
    "state":  "{{ state }}",
    "assigneeContact":  "{{ assignee }}",
    "activity":  [
                     {
                         "workLogType":  "{{ logType }}",
                         "workLogContact":  "{{ logContact }}",
                         "workLogDescription":  "{{ notes }}"
                     }
                 ]
      }'
     status_code: 200
    register: result
    when: action == "assign"
###################################################
  - name: Update Incident in ServiceNow
    uri:
     url: "{{ api_url }}"
     method: PATCH
     headers:
      Authorization: "Bearer {{ servicenow_token }}"
      Content-Type: "application/json"
     body_format: json
     body: '{
    "activity":  [
                     {
                         "workLogType":  "{{ logType }}",
                         "workLogContact":  "{{ logContact }}",
                         "workLogDescription":  "{{ notes }}"
                     }
                 ]
      }'
     status_code: 200
    #register: result
    when: action == "update"
    register: result
###################################################
  - name: De-Assign Incident in ServiceNow
    uri:
     url: "{{ api_url }}"
     method: PATCH
     headers:
      Authorization: "Bearer {{ servicenow_token }}"
      Content-Type: "application/json"
     body_format: json
     body: '{
    "assigneeContact":  "",
    "activity":  [
                     {
                         "workLogType":  "{{ logType }}",
                         "workLogContact":  "{{ logContact }}",
                         "workLogDescription":  "{{ notes }}"
                     }
                 ]
      }'
     status_code: 200
    register: response
    when: action == "deassign"
###################################################
  - name: Resolve Incident in ServiceNow
    uri:
     url: "{{ api_url }}"
     method: PATCH
     headers:
      Authorization: "Bearer {{ servicenow_token }}"
      Content-Type: "application/json"
     body_format: json
     body: '{
    "resolutionMethod":  "{{ resolutionMethod }}",
    "activity":  [
                     {
                         "workLogType":  "{{ logType }}",
                         "workLogContact":  "{{ logContact }}",
                         "workLogDescription":  "{{ notes }}"
                     }
                 ],
    "resolutionDescription":  "{{ resolutionNotes }}",
    "state": "{{ state }}"
    }'
     status_code: 200
    register: response
    when: action == "resolve"
###################################################
  - name: Check API response
    debug:
      var: status

  - name: Check API response status
    debug:
          msg: "Incident updated successfully"
    when: status ==200

  - name: Check API response status
    fail:
         msg: "Failed to update Incident. Error: {{ response.json }}"
    when: status !=200
