- name: Update ServiceNow Incident
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Include the generated token
    include_tasks: "Testtoken.yaml"
  - name: Construct URL with parameters
    set_fact:
      api_url: "{{ ipaas_uri }}uuid={{ uuid | urlencode }}&companyName={{ companyName | urlencode }}"
  - name: Update Incident in ServiceNow
    uri:
     url: "{{ api_url }}"
     method: PATCH
     headers:
      Authorization: "Bearer {{ servicenow_token }}"
      Content-Type: "application/json"
     body_format: json
     body: '{
    "state":  "{{ state }}",
    "assigneeContact":  "{{ assignee }}",
    "activity":  [
                     {
                         "workLogType":  "{{ logType }}",
                         "workLogContact":  "{{ logContact }}",
                         "workLogDescription":  "{{ notes }}"
                     }
                 ]
      }'
     status_code: 200
    register: response

  - name: Check API response
    debug:
      var: response

  - name: Check API response status
     debug:
          msg: "Incident updated successfully"
     when: response.status ==200

  - name: Check API response status
     fail:
          msg: "Failed to update Incident. Error: {{ response.json }}"
     when: response.status !=200
