- name: Update ServiceNow Incident
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Include the generated token
    include_tasks: "Testtoken.yaml"
  - name: Update Incident in ServiceNow
    uri:
     url: '{{ ipaas_uri }}'
     method: Patch
     headers:
      Authorization: "Bearer {{ servicenow_token }}"
      Content-Type: "application/json"
     body_format: json
     body: '{
    "state":  "{{ state }}",
    "assigneeContact":  "{{ assignee }}",
    "activity":  [
                     {
                         "workLogType":  "{{ logType }}",
                         "workLogContact":  "{{ logContact }}",
                         "workLogDescription":  "{{ notes }}"
                     }
                 ]
      }'
     status_code: 200
    register: response

  - name: Check API response
    debug:
      var: response
